"""BKZ 约减参数。"""

DELTA = 3 / 4

# mpmath 精度配置
AUTO_PRECISION_DIM_LOW = 150
AUTO_PRECISION_DIM_HIGH = 250
MP_DPS_LOW = 50
MP_DPS_HIGH = 100
MP_STUCK_THRESHOLD = 100
MP_MAX_RETRY = 1

PRECISION_MODE_LOW = 0
PRECISION_MODE_AUTO = 1
PRECISION_MODE_HIGH = 2
